webtalk_init -webtalk_dir C:/Users/Uqdxz/Desktop/MA/STT_MRAM_git/454/STT-MRAM.sim/blink_test/behav/xsim/xsim.dir/test_blink_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Apr  3 14:32:02 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2258646" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211953610_0_0_140" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d2e3eaae-678a-4da8-80de-a5e5b87cbf8a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "bd2e0a8d872040a2bd73914c2c5626bd" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "53" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2808 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1001 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6972_KB" -context "xsim\\usage"
webtalk_transmit -clientid 4273930180 -regid "211953610_0_0_140" -xml C:/Users/Uqdxz/Desktop/MA/STT_MRAM_git/454/STT-MRAM.sim/blink_test/behav/xsim/xsim.dir/test_blink_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Uqdxz/Desktop/MA/STT_MRAM_git/454/STT-MRAM.sim/blink_test/behav/xsim/xsim.dir/test_blink_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Uqdxz/Desktop/MA/STT_MRAM_git/454/STT-MRAM.sim/blink_test/behav/xsim/xsim.dir/test_blink_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
